apiVersion: v1
kind: ConfigMap
metadata:
  name: bankingops-config
  namespace: bankingops-dev
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: bankingops
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: prod
  LOG_LEVEL: INFO
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+UseContainerSupport"
