apiVersion: v1
kind: ConfigMap
metadata:
  name: bankingops-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  DB_HOST: postgres-service
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName }}
  SERVER_PORT: {{ .Values.api.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile }}
  LOG_LEVEL: {{ .Values.config.logLevel }}
  JAVA_TOOL_OPTIONS: >-
    -XX:MaxRAMPercentage={{ .Values.api.jvm.maxRAMPercentage }}
    -XX:InitialRAMPercentage={{ .Values.api.jvm.initialRAMPercentage }}
    -XX:+UseContainerSupport
