apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: transaction-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: transaction-api
  template:
    metadata:
      labels:
        app: transaction-api
    spec:
      containers:
        - name: transaction-api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: bankingops-config
            - secretRef:
                name: bankingops-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.api.port }}
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.api.port }}
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.liveness.failureThreshold }}
          resources:
            requests:
              memory: {{ .Values.api.resources.requests.memory | quote }}
              cpu: {{ .Values.api.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.api.resources.limits.memory | quote }}
              cpu: {{ .Values.api.resources.limits.cpu | quote }}
