apiVersion: v1
kind: Secret
metadata:
  name: bankingops-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.dbUser | b64enc }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
  SPRING_SECURITY_USER_NAME: {{ .Values.secret.securityUserName | b64enc }}
  SPRING_SECURITY_USER_PASSWORD: {{ .Values.secret.securityUserPassword | b64enc }}
