apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankingops-dev
  namespace: argocd
  labels:
    env: dev
    app: bankingops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source : le chart Helm dans le repo Git
  source:
    repoURL: http://gitea.gitea.svc.cluster.local:3000/msel/bankingops-platform.git
    targetRevision: develop
    path: helm/bankingops
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  # Destination : où déployer dans le cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: bankingops-dev

  # Politique de synchronisation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
